# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
import argparse,sys,os
parser = argparse.ArgumentParser()
parser.add_argument("--entry_point", help="sets the module where main_loop function exists")
args = parser.parse_args()
if args.entry_point is not None:
    fd=open("Private/entry_point.py","w")
    print("#Autogenerated file (by config.py) dont edit!",file=fd)
    print("import "+args.entry_point,file=fd)
    print("main_loop="+args.entry_point+".main_loop",file=fd)
    print("kill="+args.entry_point+".kill",file=fd)
    fd.close()

