//this is autogenerated file by build.py Dont Edit!!!
#pragma once
#define PYTHON_LIB "/local/ori/anaconda3/lib/libpython3.5m.so"
#define SYSPATH "/local/learn/ur4/test3prj/Plugins/PyServer/Source/PyServer/Private"
#include "/local/ori/anaconda3/include/python3.5m/Python.h"
